/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateOrderRequest {
  'serviceType' : ServiceType,
  'paymentMethod' : PaymentMethod,
  'customerDetails' : CustomerDetails,
  'pickupTime' : string,
}
export interface CustomerDetails {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type OrderId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'inProgress' : null };
export type PaymentMethod = { 'creditCard' : null } |
  { 'cash' : null } |
  { 'onlinePayment' : null };
export type ServiceType = { 'shirt' : null } |
  { 'pants' : null } |
  { 'dress' : null };
export interface TailoringOrder {
  'id' : OrderId,
  'status' : OrderStatus,
  'serviceType' : ServiceType,
  'paymentMethod' : PaymentMethod,
  'owner' : Principal,
  'customerDetails' : CustomerDetails,
  'pickupTime' : string,
  'price' : bigint,
}
export interface UserProfile {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[CreateOrderRequest], OrderId>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], TailoringOrder>,
  'getPriceEstimate' : ActorMethod<[ServiceType], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listOrders' : ActorMethod<[], Array<TailoringOrder>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];